### PR TITLE
work on media

### PR DESCRIPTION
**Pull request by voltan**

### CODE REVIEW

**Comment by voltan** [comment]
Please margin it before add new changes, I reback some parts and skip season at this time.

remove InnoDB and hide description on form is more important for me

**Comment by voltan** [comment]
@Marc-pi

**Comment by voltan** [comment]
@Marc-pi can you please margin it , I need this changes

**Comment by Marc-pi** [comment]
there is a conflict

**Comment by Marc-pi** [comment]
hope you tested everything

**Pull request merged**
